# Tenant worker core definition. For platform workers metadata configs are used to set bindings.
name = "tenant-worker-core"
compatibility_date = "2024-06-03"

find_additional_modules = true
base_dir = ".mesh"
rules = [
  { type = "CommonJS", globs = ["tenantFiles/**/*.js"] }
]

kv_namespaces = [
  { binding = "MESH_KV_NAMESPACE", id = "local-kv" }
]

[vars]
# State configuration
MAX_STATE_KEY_SIZE_BYTES="512" # 512 bytes
MAX_STATE_VALUE_SIZE_BYTES="1048576" # 1 MiB
MIN_STATE_TTL_SECONDS="60" # 1 minute
MAX_STATE_TTL_SECONDS="604800" # 7 days
