name: lint-build-test
on:
  push:
  pull_request:
      types: [closed, opened, edited]
      branches:
          - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        # - uses: jfrog/setup-jfrog-cli@v3
        #   env:
        #     JF_URL: ${{ secrets.JF_URL }}
        #     JF_USER: ${{ secrets.JF_USER }}
        #     JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 18
        - run: npm install -g @adobe/aio-cli
        - run: npm install
        - run: npm run lint
        - run: aio config set cli.env stage
        - run: npm test
