name: lint-build-test
on:
  push:
  pull_request:
      types: [closed, opened, edited]
      branches:
          - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        # - uses: jfrog/setup-jfrog-cli@v3
        #   env:
        #     JF_URL: ${{ secrets.JF_URL }}
        #     JF_USER: ${{ secrets.JF_USER }}
        #     JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 22
        - run: yarn global add @adobe/aio-cli
        - run: yarn install --frozen-lockfile
        - run: yarn run lint
        - run: aio config set cli.env stage
        - run: xvfb-run yarn run test
