name: publish-to-npm
on:
    push:
        branches:
            - main # Change this if not your default branch
jobs:
    publish:
        if: github.repository == 'adobe/aio-cli-plugin-api-mesh'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: npm install
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
                  access: 'public'
