name: publish-to-npm
on:
    pull_request:
        types: [closed]
        branches:
            - main
jobs:
    publish:
        if: github.repository == 'adobe/aio-cli-plugin-api-mesh'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: yarn install --frozen-lockfile
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
                  access: 'public'
                  tag: 'beta'
